#./ docker-compose.yml 
# version: '3.8'
version: "3.9"
services : 
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  #root password
      - MYSQL_DATABASE=${MYSQL_DATABASE}  # database name
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  web:
    container_name: fastapi_web
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    depends_on:  # 데이터베이스
        db:
          condition: service_healthy   # 의존성 조건 변경
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/templates --reload-include "*.html"

    volumes:
        - ./app:/app


volumes:
  mysql_data:  # ✅ 꼭 필요함! 없으면 오류 남